### ISSUE TITLE
pls make it portal track when the speedrunner goes to the nether or end. And pls make it track them in the nether if it does not.

### ISSUE THREAD

**Issue by ScreamsEcho** [NateKomodo/DreamManHunt#22] opened 2021-02-22 06:07 UTC
## Some information
Operating system (client): 
Java version (client): 
Operating system (server): 
Java version (server): 
Minecraft version:
Plugin version: 
Forge mods (if used): 
Other plugins (if used): 

## Exception, error or logs
Please find your `latest.log` attach it to the issue

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have filled in all the sections.
- [ ] I have included logs, exceptions and / or steps to reproduce the issue.

**Comment by NateKomodo** [comment] 2021-02-22 12:32
Duplicate of #16

**Closed as completed by NateKomodo** 2021-02-22 12:32 UTC
